---
name: Run Commands on Docker Images

on:
  push:
    branches:
      - master

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - nginx
          - memcached
          - busybox
          - alpine
          - ubuntu
          - redis
          - postgres
          - python
          - node
          - httpd
          - mongo
          - mysql
          - rabbitmq
          - docker
          - hello-world
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | \
            sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: |
          syft ${{ matrix.image }} \
            -o cyclonedx-json > ${{ matrix.image }}-sbom_cyclonedx.json

          syft ${{ matrix.image }} \
            -o spdx-json > ${{ matrix.image }}-sbom_spdx.json

      - name: Upload CycloneDX SBOM
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image }}-cyclonedx
          path: ${{ matrix.image }}-sbom_cyclonedx.json

      - name: Upload SPDX SBOM
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image }}-spdx
          path: ${{ matrix.image }}-sbom_spdx.json
