---
name: Run Commands on Docker Images

on:
  push:
    branches:
      - main

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - nginx
          - memcached
          - busybox
          - alpine
          - ubuntu
          - redis
          - postgres
          - python
          - node
          - httpd
          - mongo
          - mysql
          - rabbitmq
          - docker
          - hello-world
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run command on Docker image
        run: |
          echo "Running command on ${{ matrix.image }}"
          docker pull ${{ matrix.image }}
          docker sbom \
            --format cyclonedx-json \
            -o ${{ matrix.image }-cyclonedx.json \
            ${{ matrix.image }}
